apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          limits:
            memory: 1024Mi
            cpu: 1
          requests:
            memory: 512Mi
            cpu: 500m

